In [ ]:
a=12
b=13
c=a&b
print(c)

12


In [ ]:
c='hi hehe'
print(c.title())

Hi Hehe


In [ ]:
c='hello pro'
c.find('pro')

6

In [ ]:
c=' python programming'
print(c.strip())

python programming


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))
print(len(arr))
print(arr.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
4
(4,)


In [ ]:
x=np.array([1,4,3])
y=np.append(x,[50,60])
print(y)
z=np.delete(y,3)
print(z)
u=np.sort(x)
print(u)

[ 1  4  3 50 60]
[ 1  4  3 60]
[1 3 4]


In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print(arr_2d.shape)
print(arr_2d.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [ ]:
#indexing
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d[1,2])
print(arr_2d[1,1:5])
print(arr_2d[0:2,1:5])
print(arr_2d[:.1]) #column
print(arr_2d[0,]) #row

6
[5 6]
[[2 3]
 [5 6]]


In [ ]:

import sympy as smp
from sympy import *
x, y= smp.symbols('x y') #epuation er moto likhar jonno use kora hoy
x**2+y


x**2 + y

In [ ]:
smp.sin(x/2)+ smp.sin(x)

sin(x/2) + sin(x)

In [ ]:
import numpy as np ##numpy and sympy ek sathe use korar jonno lamdify use kora hoi
f=2*x**3+x**2+3*x+5
f=lambdify(x,y)
test_number=np.arange(1,11)
print(test_number)
a=f(test_number)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
y


In [2]:
import sympy as smp #integration er niyom
import numpy as np
import scipy as sp
x= smp.symbols("x")
f= smp.exp(-x)*(x**2)*smp.cos(x)
smp.integrate(f,x)

x**2*exp(-x)*sin(x)/2 - x**2*exp(-x)*cos(x)/2 + x*exp(-x)*sin(x) + exp(-x)*sin(x)/2 + exp(-x)*cos(x)/2

In [3]:
smp.integrate(f,x).simplify()

sqrt(2)*(-x**2*cos(x + pi/4) + x*sin(x + pi/4) - x*cos(x + pi/4) + sin(x + pi/4))*exp(-x)/2

In [8]:
x= smp.symbols("x")
f=smp.sin(x)**3*smp.exp(-5*x)
smp.integrate(f,x)

-40*exp(-5*x)*sin(x)**3/221 - 21*exp(-5*x)*sin(x)**2*cos(x)/221 - 15*exp(-5*x)*sin(x)*cos(x)**2/442 - 3*exp(-5*x)*cos(x)**3/442

In [10]:
f= smp.exp(-smp.sin(x))
smp.integrate(f,(x,1,2))

Integral(exp(-sin(x)), (x, 1, 2))

In [11]:
from scipy.integrate import quad
def f(x):
  return x
area=quad(f,0,2)
print(area)

(2.0, 2.220446049250313e-14)


In [13]:
from scipy.integrate import dblquad
def f(x,y):
  return x*y
area=dblquad(f,0,2,0,5)
print(area)


(25.0, 2.7755575615628914e-13)


In [14]:
f=lambda x,y :x*y
area=dblquad(f,0,2,0,5)
print(area)

(25.0, 2.7755575615628914e-13)
