In [ ]:
import numpy as np
arr=np.array([1, 2, 3, 4])
print(arr)
print(len(arr))

print(arr.shape)

[1 2 3 4]
4
(4,)


In [ ]:
#append

x=np.array([1, 2, 3, 4])
y=np.append(x, [50, 20])
print(y)


[ 1  2  3  4 50 20]


In [ ]:
#delete(array, index)
y=np.delete(x, 3)
print(y)

[1 2 3]


In [ ]:
#sorting

x=np.array([5, 3, 7, 2])
sorted_x=np.sort(x)
print(sorted_x)
print(sorted_x[::-1])

[2 3 5 7]
[7 5 3 2]


In [ ]:
#2d array

arr_2d=np.array([[1, 2, 3, 11, 12], [4, 5, 6, 9, 10]])
print(arr_2d)
print(len(arr_2d))
print(arr_2d.shape)

[[ 1  2  3 11 12]
 [ 4  5  6  9 10]]
2
(2, 5)


In [ ]:
print(arr_2d[1, 2])
print(arr_2d[1, 0:3])
print(arr_2d[0:2, 1:4])
print(arr_2d[:, 1])
print(arr_2d[0, ])

6
[4 5 6]
[[ 2  3 11]
 [ 5  6  9]]
[2 5]
[ 1  2  3 11 12]


In [ ]:
 #sympy
#limit

import sympy as smp
from sympy import *
x, y= smp.symbols('x y') #epuation er moto likhar jonno use kora hoy
x**2+y



x**2 + y

In [ ]:
#substitution korar jonno
f=x**2+y
f.subs(x, 4)

y + 16

In [ ]:
#sin, cos, tan etc er jonno
x, y=smp.symbols('x y')
smp.asin(x) #trigino matric funt
smp.exp(x) #e^xe
smp.log(x, 10) #log(x)/ log 10
x**(smp.Rational(3, 2)) #rational x^3/2 er nonno
x**(3/2) #irrational x^1.5 er jonno

x**1.5

In [ ]:
smp.sin(x/2)+ smp.sin(x)

sin(x/2) + sin(x)

In [ ]:
smp.limit(smp.sin(x/2)+sin(x),  x, smp.pi)  #lim x-->pi then sin(x/2)+sin(x)

1

In [ ]:
#lim x-->0+ then (2e^(1/x))/(e^(1/x)+1)
smp.limit((2*smp.exp(1/x))/(smp.exp(1/x)+1), x, 0, dir='+')

2

In [ ]:
#lim x--> infinity (cos(x)-1)/x
smp.limit((smp.cos(x)-1)/x, x, smp.oo)

0

In [ ]:
#derivatives
#d/dx((1+sinx)/(1-cosx))^2

smp.diff(((1+smp.sin(x))/(1-smp.cos(x)))**2, x)

2*(sin(x) + 1)*cos(x)/(1 - cos(x))**2 - 2*(sin(x) + 1)**2*sin(x)/(1 - cos(x))**3

In [ ]:
#another way to do the derivatives
x=symbols('x')
f=2*x**3+x**2+3*x+5
df_first=diff(f, x)
df_second=diff(f, x, 2)
print(df_first)
print(df_second)
print(f.subs(x, 4))
print(df_first.subs(x, 4))

6*x**2 + 2*x + 3
2*(6*x + 1)
161
107


In [ ]:
#multple variable er jonno
x, y, z=symbols('x y z')
expr=x**3+4*x*y-z
exprvalue=expr.subs([(x, 2), (y, 4), (z, 2)])
dfExpr=diff(expr, x)
df2Expr=diff(expr, x, 2)
print(exprvalue)
print(dfExpr)
print(df2Expr)
dfExpr_y=diff(expr, y)
df2Expr_y=diff(expr, y, 2)
print(dfExpr_y)
print(df2Expr_y)

38
3*x**2 + 4*y
6*x
4*x
0


In [ ]:
#numpy and sympy ek sathe use korar jonno lamdify use kora hoi
import numpy as np
f=2*x**3+x**2+3*x+5
f=lambdify(x,f)
test_numbers=np.arange(1, 11)
print(test_numbers)
a=f(test_numbers)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[  11   31   77  161  295  491  761 1117 1571 2135]


In [ ]:
#y=f(x)=2x^3-6x^2-18x+7 maximapoint(-1, 17) minima(3, -47) minima -47 and maxima 17

from sympy import *

x = Symbol('x')
f_x=2*x**3-6*x**2-18*x+7
first_diff=diff(f_x, x)
# second_diff=diff(f_x, x, 2)
a=solve(first_diff, x)
for i in a:
    if i<0:
        maxima= f_x.subs(x, i)
        print(f'Maxima is {maxima} and maximapoint is {i, maxima}.')
    elif i>0:
        minima=f_x.subs(x, i)
        print(f'Minima is {minima} and minimapoint is {i, minima}.')
    else:
        print('In conclusive.')


Maxima is 17 and maximapoint is (-1, 17).
Minima is -47 and minimapoint is (3, -47).


In [8]:
from sympy.concrete.summations import solveset
#maxima and minima by madam

import sympy as smp
import numpy as np
x=smp.symbols('x')
f_x=9*x**3-7*x**2+3*x+10
# df=smp.diff(f_x, x)
df=smp.Eq(f_x.diff(x))
display(df)
# display(df)
solveset(df, x)

/usr/local/lib/python3.7/dist-packages/sympy/core/relational.py:496: SymPyDeprecationWarning: 

Eq(expr) with rhs default to 0 has been deprecated since SymPy 1.5.
Use Eq(expr, 0) instead. See
https://github.com/sympy/sympy/issues/16587 for more info.

  deprecated_since_version="1.5"


Eq(27*x**2 - 14*x + 3, 0)

FiniteSet(7/27 - 4*sqrt(2)*I/27, 7/27 + 4*sqrt(2)*I/27)

In [12]:
smp.limit(2*smp.exp(1/x)/(smp.exp(1/x)+1),x,0,dir='+')

2